# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Popcorn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Popcorn
  pod 'AFNetworking', '~> 3.1'
  pod 'SDWebImage', '~> 3.8'
  pod 'FBSDKCoreKit', '~> 4.18'
  pod 'FBSDKShareKit', '~> 4.18'
  pod 'FBSDKLoginKit', '~> 4.18'
#  pod 'GoogleAnalytics', '~> 3.17'

  target 'PopcornTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PopcornUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
